name: skynet
description: Use Sia Skynet and SkyDB in your Dart and Flutter projects
  (Decentralized CDN and database)
version: 4.0.0
homepage: https://github.com/redsolver/skynet

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cryptography: ^2.0.1
  http: ^0.13.0
  fixnum: ^1.0.0-nullsafety.0
  convert: ^3.0.0
  http_parser: ^4.0.0
  crypto: ^3.0.0
  web_socket_channel: ^2.0.0
  pinenacl: ^0.2.0-nullsafety.9
  mime: ^1.0.0
  password_hash:
    git: https://github.com/Derrick56007/dart-password-hash.git
  js: ^0.6.3
  json_annotation: ^4.0.0
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.16.5
  build_runner: ^1.0.0
  json_serializable: ^4.0.0

dependency_overrides:
  fixnum: ^1.0.0
  convert: ^3.0.0
  crypto: ^3.0.0
